<?php

use Illuminate\Database\Seeder;
use App\Clase;

class ClaseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Clase::create([
           'name' => 'Mago',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

            

       App\Clase::create([
           'name' => 'Guerrero',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

       App\Clase::create([
           'name' => 'Picaro',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

       App\Clase::create([
           'name' => 'Paladin',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

       App\Clase::create([
           'name' => 'Clerigo',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

       App\Clase::create([
           'name' => 'Arquero',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);

       App\Clase::create([
           'name' => 'Cazador',
           'fuerza' => 0,
            'agilidad' => 0,
            'inteligencia' => 0,
            'constitucion' => 0,
            'stamina' => 0,
            'carisma' => 5,
            'suerte' => 0,
            'evasion' => 5,
            'supervivencia' => 0,
            'defensa' => 0,
            'resMagica' => 15,
            'domesticar' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'combateArms' => 0,
            'combateDist' => 0,
            'probCritico' => 0,
            'dannoCritico' => 0,
            'bloqueo' => 0,
            'regVida' => 0,
            'regEnergia' => 0,
            'regMana' => 10,
            'velAtaque' => 0,
            'pesca' => 0,
            'manaExtra' => 50,
            'mineria' => 0,
            'herreria' => 0,
            'carpinteria' => 0,
            'sastreria' => 0
       ]);
    }
}
